Repository languagetool-org/languagetool, pull requests merged in 2023-11, with the labels that each got.

#9573 [pt] Complete rewrite of rule ID:IR_CONTRACTION_NOUN
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Labels: Portuguese

#9536 [pt] Added rule ID:PELO_QUAL_PELA_QUAL and rule ID:PELA_QUAL_PELO_QUAL
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Labels: Portuguese

#9558 [pt] Added rule ID:CONFUSÃO_AO_OU
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Labels: Portuguese

#9583 [pt] Added AP to rule ID:CRASE_CONFUSION
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Labels: Portuguese

#9554 [pt] Moved and improved rules from wordiness.txt to rule ID:QUALQUER_QUE_SEJA_FOSSE_INDEPENDENTEMENTE
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/wordiness.txt
Labels: Portuguese

#9592 [pt] Rewrote rule ID:MUITO_FRIO
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Labels: Portuguese

#9593 [pt] Rewrote rule ID:É_IGUAL_AO_LITRO
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Labels: Portuguese

#9595 [pt] Added words to spelling.txt
  languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/hunspell/spelling.txt
Labels: Portuguese

#9591 [pt] Added rule ID:QUASE_QUE_PRONOME_QUASE_PRONOME
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Labels: Portuguese

#9597 [pt] Recommit of rule ID:DIFERENTES
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Labels: Portuguese

#9601 [pt] Added exceptions to rule ID:CONFUSÃO_ESTA_ESTÁ (soon I must join both rules into one)
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Labels: Portuguese

#9602 [pt] Improved rule ID:AFEAR
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Labels: Portuguese

#9615 [pt-PT] Removed temp_off from rule ID:É_IGUAL_AO_LITRO
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
Labels: Portuguese

#9628 [pt] Added antipattern to rule ID:GENERAL_NUMBER_AGREEMENT_ERRORS
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Labels: Portuguese

#9633 [pt] Rewrote rule ID:ESTAR_NO_ECRA
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Labels: Portuguese

#9661 [pt-PT] Improved slightly rule ID:ERRO_TRADUÇÃO_FURTO_ROUBO_IDENTIDADE
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
Labels: Portuguese

#9662 [pt-PT] Improved slightly rule ID:ERRO_TRADUÇÃO_ESTIMAÇÃO_MÁXIMA_SEMELHANÇA_PT_PT
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
Labels: Portuguese

#9617 [pt] Fixed 2 FPs and removed "temp_off" from rule ID:QUALQUER_QUE_SEJA
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Labels: Portuguese

#9621 [pt] Removed "temp_off" from rule ID:INIMIGO_ADVERSÁRIO_ALIADO_OPONENTE
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Labels: Portuguese

#9623 [pt-PT] Added rule ID:SIMPLIFICAR_A_SER_PP_A_INF
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
Labels: Portuguese

#9650 [pt] Another attempt to recommit rule ID:CAUSAR_DIFICULDADE_DIFICULTAR
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Labels: Portuguese

#9652 [pt] Added words to wordiness.txt
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/wordiness.txt
Labels: Portuguese

#9649 [pt] Added rule ID:REMOÇÃO_SUBSTANTIVO_APÓS_MESMO
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Labels: Portuguese

#9651 [pt] Rewrote rule ID:TRABALHO_PAGO_REMUNERADO
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Labels: Portuguese

#9705 [es] add words to dict
  languagetool-language-modules/es/src/main/resources/org/languagetool/resource/es/added.txt
  languagetool-language-modules/es/src/main/resources/org/languagetool/resource/es/hunspell/spelling.txt
Labels: Spanish

#9706 [es] updated ignore.txt
  languagetool-language-modules/es/src/main/resources/org/languagetool/resource/es/hunspell/ignore.txt
Labels: Spanish

#9708 [pt] Removed rule ID:MADRUGADA_MATINAL
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Labels: Portuguese

#9709 [pt] Added AP to rule ID:GENERAL_NUMBER_AGREEMENT_ERRORS
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Labels: Portuguese

#9711 [pt-PT] Added exception to rule ID:SIMPLIFICAR_QUE_VERBO_A_VERBOINFINITIVO
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
Labels: Portuguese

#9713 [pt] Added antipatterns to rule ID:COLOCAÇÃO_ADVÉRBIO and rule ID:COLOCACAO_ADVÉRBIO_VERBO_ANTES
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Labels: Portuguese

#9710 [pt] Added exception to rule ID:ESTA_ESTÁ
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Labels: Portuguese

#9734 [de] extend disambiguation rule HAEUFIGE_NACHNAMEN
  languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/disambiguation.xml
  languagetool-language-modules/de/src/main/resources/org/languagetool/resource/de/multitoken-ignore.txt
Labels: German

#9741 [pt] Added AP to rule ID:SENDO_PARTPASS_PARTPASS
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Labels: Portuguese

#9747 [pt] Removed "temp_off" from rule ID:PELO_QUAL_PELA_QUAL
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Labels: Portuguese

#9748 [pt] Removed "temp_off" from rule ID:TRABALHO_PAGO_REMUNERADO
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Labels: Portuguese

#9749 [pt] Removed "temp_off" from rule ID:QUASE_QUE_PRONOME
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Labels: Portuguese

#9750 [pt] Removed "temp_off" from rule ID:MUITO_FRIO
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Labels: Portuguese

#9753 [pt] Removed "temp_off" from rule ID:REMOÇÃO_SUBSTANTIVO_APÓS_MESMO
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Labels: Portuguese

#9754 [pt] Removed "temp_off" from rule ID:CONFUSÃO_AO_OU
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Labels: Portuguese

#9746 [pt] Removed "temp_off" from rule ID:ESTAR_NO_ECRA
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Labels: Portuguese

#9766 [pt] Improved AP in rule ID:SIMPLIFICAR_QUE_E_TEM_TÊM
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/style.xml
Labels: Portuguese

#9762 [pt] add rulegroup CONCORDANCIA_DETERMINANTES_MASCULINOS for multiple determiner errors
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Labels: Portuguese

#9745 [pt] Add a few confusion rules
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Labels: Portuguese

#9784 [pt] Add AP to GENERAL_VERB_AGREEMENT_ERRORS
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Labels: Portuguese

#9783 [pt] Add CONFUSAO_EU_SAI_SAÍ
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Labels: Portuguese

#9782 [pt] Add APs to NON_IMPERSONAL_VERBS
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Labels: Portuguese

#9788 [pt] add improvements to CONCORDANCIA_SER_PLURAL
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Labels: Portuguese

#9793 [pt-PT] Removed "temp_off" from rule ID:SIMPLIFICAR_A_SER_PP_A_INF
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-PT/style.xml
Labels: Portuguese
