Repository languagetool-org/languagetool, pull requests merged in 2024-02, with the labels that each got.

#10286 [fr] Update speller tests
  languagetool-language-modules/fr/src/test/java/org/languagetool/rules/fr/MorfologikFrenchSpellerRuleTest.java
Labels: French

#10312 [pt] Fix message of REFLEXIVE_VERB_SE_AGREEMENT
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/grammar.xml
Labels: Portuguese

#10319 [pt] Remove entender/intender pair from wrongWordInContext
  languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/wrongWordInContext.txt
Labels: Portuguese

#10341 [pt] Add a couple of spelling hotfixes
  languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/entities/languages.ent
  languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/spelling.txt
  languagetool-language-modules/pt/src/test/java/org/languagetool/rules/pt/MorfologikPortugueseSpellerRuleTest.java
Labels: Portuguese

#10343 en ALL_OF_THE: soften the message, make the shortest example less controversial, make the rule work at the sentence start
  languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/style.xml
Labels: English

#10355 [pt] Add hotfix for verossimilhança
  languagetool-language-modules/pt/src/main/resources/org/languagetool/resource/pt/spelling.txt
Labels: Portuguese
